[package]
name = "nif"
version = "0.5.0"
edition = "2021"
authors = ["Romet Tagobert <sgzfxn@gmail.com>"]
categories = []
description = "A super-primitive Gamebryo NIF parser targeting version 20.0.0.4"
homepage = "https://github.com/amPerl/nif"
repository = "https://github.com/amPerl/nif"
license = "MIT"
readme = "README.md"
exclude = ["tests/*"]

[features]
default = []
glam = ["dep:glam"]

[dependencies]
thiserror = "1.0.43"
binrw = "0.14.0"
glam = { version = "0.28.0", optional = true }

[dev-dependencies]
anyhow = "1.0.72"
