[package]
name = "nif"
version = "0.1.1"
edition = "2018"
authors = ["Romet Tagobert <sgzfxn@gmail.com>"]
categories = []
description = "A super-primitive Gamebryo NIF parser targeting version 20.0.0.4"
homepage = "https://github.com/amPerl/nif"
repository = "https://github.com/amPerl/nif"
license = "MIT"
readme = "README.md"
exclude = [
    "tests/*"
]

[dependencies]
anyhow = "1.0.38"
binread = "1.4.1"
thiserror = "1.0.23"
