[package]
name = "nif"
version = "0.6.0"
edition = "2021"
authors = ["Romet Tagobert <sgzfxn@gmail.com>"]
categories = []
description = "A super-primitive Gamebryo NIF parser targeting version 20.0.0.4"
homepage = "https://github.com/amPerl/nif"
repository = "https://github.com/amPerl/nif"
license = "MIT"
readme = "README.md"
exclude = ["tests/*"]

[features]
default = []
glam = ["dep:glam"]
facet = ["dep:facet", "dep:facet-reflect"]

[dependencies]
thiserror = "2.0.20"
binrw = "0.15.2"
glam = { version = "0.33.3", optional = true }
facet = { version = "0.50.0-rc.6", optional = true, features = ["reflect"] }
facet-reflect = { version = "0.50.0-rc.6", optional = true }

[dev-dependencies]
anyhow = "1.0.104"
